StylesPath = .github/styles
MinAlertLevel = suggestion

[*.md]
BasedOnStyles = Vale

# Project-specific vocabulary
Vocab = Base

# Checks
Vale.Terms = YES
Vale.Avoid = YES

[formats]
markdown = markdown
