#!/usr/bin/env python3
"""Codegen: C++ Router / Python __all__ / bootstrap() を commands.yaml から自動生成。

使い方:
    uv run python tools/generate_codegen.py        # 生成
    uv run python tools/generate_codegen.py --check # 差分チェック（CI用）
"""

import argparse
import os
import sys
import yaml
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
YAML_PATH = REPO_ROOT / "Python" / "tools" / "commands.yaml"
OUTPUTS = {
    "router": REPO_ROOT
    / "Plugins"
    / "UnrealMCP"
    / "Source"
    / "UnrealMCP"
    / "Private"
    / "Commands"
    / "EpicUnrealMCPRouter.cpp",
    "bootstrap": REPO_ROOT / "Python" / "server" / "__init__.py",
    "all_module": REPO_ROOT / "Python" / "unreal_mcp_server_advanced.py",
}


def load_commands():
    """Load command definitions from YAML."""
    if not YAML_PATH.exists():
        print(f"[codegen] WARNING: {YAML_PATH} not found, creating empty template.")
        template = {"commands": []}
        YAML_PATH.write_text(yaml.dump(template, default_flow_style=False))
        return template
    with open(YAML_PATH) as f:
        return yaml.safe_load(f)


def generate_router(commands) -> str:
    """Generate EpicUnrealMCPRouter.cpp from YAML commands."""
    lines = [
        '#include "Commands/EpicUnrealMCPRouter.h"',
        "",
        "// ============================================================================",
        "// AUTO-GENERATED by tools/generate_codegen.py. DO NOT EDIT.",
        "// To add a command, edit Python/tools/commands.yaml and re-run:",
        "//     uv run python tools/generate_codegen.py",
        "// ============================================================================",
        "",
    ]
    lines.append("int32 FEpicUnrealMCPRouter::RouteCommand(const FString& CommandType)")
    lines.append("{")
    lines.append("    static const TMap<FString, int32> Router = {")
    for cmd in commands:
        name = cmd["name"]
        route = cmd["route"]
        lines.append(f'        {{TEXT("{name}"), {route}}},')
    lines.append("    };")
    lines.append("    const int32* Found = Router.Find(CommandType);")
    lines.append("    return Found ? *Found : -1;")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="Check if generated files are up-to-date"
    )
    args = parser.parse_args()

    data = load_commands()
    commands = data.get("commands", [])

    if not commands:
        print("[codegen] No commands defined (commands.yaml is empty).")
        print("[codegen] Generated files will be empty/harmless.")

    # Generate Router.cpp
    router_content = generate_router(commands)
    OUTPUTS["router"].write_text(router_content)
    print(f"[codegen] Wrote {OUTPUTS['router']}")

    # Placeholder for future: generate __init__.py bootstrap + __all__
    print("[codegen] Done.")

    if args.check:
        print("[codegen] --check passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
