"""E2E test: generate a medieval European castle from scratch for siege warfare.

Requires:
    - SurrealDB on ws://127.0.0.1:8000
    - scene-syncd on http://127.0.0.1:8787
    - Unreal Editor with MCP Bridge on 127.0.0.1:55557

Run:
    pytest tests/e2e/test_castle_generation.py --skip-unreal   # DB + planner only
    pytest tests/e2e/test_castle_generation.py                  # Full E2E with Unreal
"""

import json
import time
import pytest

from .conftest import api_post, api_get, unreal_command, assert_success, SCENE_SYNCD_URL


class TestCastleGenerationDBOnly:
    """Tests requiring only scene-syncd (no Unreal)."""

    def test_castle_objects_bulk_upsert_and_plan(self, scene_syncd_available):
        """Create a medieval castle scene in DB and verify the sync plan shows CREATEs."""
        if not scene_syncd_available:
            pytest.skip("scene-syncd not available")

        suffix = time.strftime("%Y%m%d%H%M%S")
        scene_id = f"castle_db_{suffix}"

        api_post("/scenes/create", {
            "scene_id": scene_id,
            "name": f"Medieval Castle DB Test {suffix}",
            "description": "Siege warfare castle (DB-only test)",
        })

        try:
            objects = _build_castle_objects(scene_id, suffix)
            assert_success(
                api_post("/objects/bulk-upsert", {"scene_id": scene_id, "objects": objects}),
                "bulk upsert castle objects",
            )

            plan = api_post("/sync/plan", {"scene_id": scene_id})
            data = assert_success(plan, "plan castle")
            creates = [op for op in data.get("operations", []) if op.get("action") == "create"]
            assert len(creates) >= len(objects), \
                f"Expected >= {len(objects)} CREATEs, got {len(creates)}"
        finally:
            # Best-effort cleanup
            try:
                obj_list = api_post("/objects/list", {"scene_id": scene_id}).get("data", {}).get("objects", [])
                for obj in obj_list:
                    try:
                        api_post("/objects/delete", {"scene_id": scene_id, "mcp_id": obj.get("mcp_id", "")})
                    except Exception:
                        pass
            except Exception:
                pass


@pytest.mark.requires_unreal
class TestCastleGenerationWithUnreal:
    """Tests requiring a running Unreal Editor session."""

    def test_generate_medieval_castle(self, scene_syncd_available, unreal_available):
        """Build a medieval European castle in Unreal from scratch via scene-syncd + direct commands."""
        if not scene_syncd_available:
            pytest.skip("scene-syncd not available")
        if not unreal_available:
            pytest.skip("Unreal not available")

        suffix = time.strftime("%Y%m%d%H%M%S")
        scene_id = f"castle_{suffix}"

        # 1. Create scene
        api_post("/scenes/create", {
            "scene_id": scene_id,
            "name": f"Medieval Castle {suffix}",
            "description": "Siege warfare castle generated by E2E test",
        })

        try:
            # 2. Build castle objects in DB
            objects = _build_castle_objects(scene_id, suffix)
            assert_success(
                api_post("/objects/bulk-upsert", {"scene_id": scene_id, "objects": objects}),
                "bulk upsert castle objects",
            )

            # 3. Plan should show all CREATEs
            plan = api_post("/sync/plan", {"scene_id": scene_id})
            plan_data = assert_success(plan, "plan castle")
            creates = [op for op in plan_data.get("operations", []) if op.get("action") == "create"]
            assert len(creates) >= len(objects), \
                f"Expected >= {len(objects)} CREATEs, got {len(creates)}"

            # 4. Apply to Unreal
            apply_data = _apply_castle_scene(scene_id)
            summary = apply_data["summary"]
            assert summary["creates"] >= len(objects), \
                f"Expected >= {len(objects)} creates, got {json.dumps(summary, indent=2)}"

            # 5. Verify each castle actor exists in Unreal.
            # Query once rather than issuing one socket command per actor; the
            # bridge can abort bursts of short-lived TCP verification calls.
            missing_mcp_ids = _missing_castle_mcp_ids(objects)
            if missing_mcp_ids:
                # The editor bridge can report a create before the actor is
                # visible in the next level snapshot. Re-plan/apply once so
                # scene-syncd converges missing desired objects.
                _apply_castle_scene(scene_id)
                for _ in range(5):
                    missing_mcp_ids = _missing_castle_mcp_ids(objects)
                    if not missing_mcp_ids:
                        break
                    time.sleep(0.5)
            assert not missing_mcp_ids, \
                f"Castle actors missing in Unreal: {missing_mcp_ids}"

            # 6. Create NavMesh for the inner courtyard
            nav_result = unreal_command("create_nav_mesh_volume", {
                "volume_name": f"CastleNavMesh_{suffix}",
                "location": [0.0, 0.0, 0.0],
                "extent": [4500.0, 4500.0, 500.0],
            })
            nav_inner = nav_result.get("result", {})
            assert nav_inner.get("success") is not False, \
                f"NavMesh creation failed: {nav_result}"
            assert nav_inner.get("navmesh_rebuilt") is True, \
                f"NavMesh not rebuilt: {nav_result}"

            # 7. Create patrol route along the top of the walls
            patrol_result = unreal_command("create_patrol_route", {
                "patrol_route_name": f"CastleWallPatrol_{suffix}",
                "points": [
                    {"x": -4000.0, "y": -4000.0, "z": 800.0},
                    {"x": 4000.0, "y": -4000.0, "z": 800.0},
                    {"x": 4000.0, "y": 4000.0, "z": 800.0},
                    {"x": -4000.0, "y": 4000.0, "z": 800.0},
                ],
                "closed_loop": True,
            })
            patrol_inner = patrol_result.get("result", {})
            assert patrol_inner.get("success") is not False, \
                f"Patrol route creation failed: {patrol_result}"
            assert patrol_inner.get("point_count") == 4, \
                f"Patrol route point count mismatch: {patrol_result}"

            # 8. Set AI behavior for the north-west tower guard
            tower_nw_name = f"CastleTowerNW_{suffix}"
            ai_result = unreal_command("set_ai_behavior", {
                "actor_name": tower_nw_name,
                "faction": "hostile",
                "behavior_tree_path": "/Game/AI/BT_CastleGuard.BT_CastleGuard",
                "perception_radius": 2000.0,
            })
            # The behavior tree may not exist in the project; allow that error,
            # but verify the actor was found and tags were applied.
            ai_inner = ai_result.get("result", {})
            error = ai_inner.get("error", "")
            assert "Actor not found" not in str(error), \
                f"Tower guard actor not found for AI setup: {ai_result}"

        finally:
            # Cleanup: delete all objects from DB and apply to Unreal
            try:
                obj_list = api_post("/objects/list", {"scene_id": scene_id}).get("data", {}).get("objects", [])
                for obj in obj_list:
                    try:
                        api_post("/objects/delete", {"scene_id": scene_id, "mcp_id": obj.get("mcp_id", "")})
                    except Exception:
                        pass
                api_post("/sync/apply", {
                    "scene_id": scene_id,
                    "mode": "apply_safe",
                    "allow_delete": True,
                    "max_operations": 200,
                })
            except Exception:
                pass


def _build_castle_objects(scene_id: str, suffix: str):
    """Return a list of castle objects for bulk-upsert.

    Coordinate system: Unreal cm units.
    Castle footprint: 100m x 100m (scale 100 = 10,000cm).
    mcp_ids include the suffix so each test run is independent.
    """
    objs = []

    # --- Ground plane ---
    objs.append({
        "scene_id": scene_id,
        "mcp_id": f"castle_ground_{suffix}",
        "desired_name": f"CastleGround_{suffix}",
        "actor_type": "StaticMeshActor",
        "asset_ref": {"path": "/Engine/BasicShapes/Plane.Plane"},
        "transform": {
            "location": {"x": 0.0, "y": 0.0, "z": -50.0},
            "rotation": {"pitch": 0.0, "yaw": 0.0, "roll": 0.0},
            "scale": {"x": 100.0, "y": 100.0, "z": 1.0},
        },
        "tags": ["castle", "ground"],
    })

    # --- Outer walls (10m thick, 8m high) ---
    # North wall
    objs.append({
        "scene_id": scene_id,
        "mcp_id": f"castle_wall_north_{suffix}",
        "desired_name": f"CastleWallNorth_{suffix}",
        "actor_type": "StaticMeshActor",
        "asset_ref": {"path": "/Engine/BasicShapes/Cube.Cube"},
        "transform": {
            "location": {"x": 0.0, "y": -4500.0, "z": 400.0},
            "rotation": {"pitch": 0.0, "yaw": 0.0, "roll": 0.0},
            "scale": {"x": 50.0, "y": 10.0, "z": 4.0},
        },
        "tags": ["castle", "wall"],
    })
    # South wall east segment (gate opening in centre)
    objs.append({
        "scene_id": scene_id,
        "mcp_id": f"castle_wall_south_east_{suffix}",
        "desired_name": f"CastleWallSouthEast_{suffix}",
        "actor_type": "StaticMeshActor",
        "asset_ref": {"path": "/Engine/BasicShapes/Cube.Cube"},
        "transform": {
            "location": {"x": 3000.0, "y": 4500.0, "z": 400.0},
            "rotation": {"pitch": 0.0, "yaw": 0.0, "roll": 0.0},
            "scale": {"x": 20.0, "y": 10.0, "z": 4.0},
        },
        "tags": ["castle", "wall"],
    })
    # South wall west segment
    objs.append({
        "scene_id": scene_id,
        "mcp_id": f"castle_wall_south_west_{suffix}",
        "desired_name": f"CastleWallSouthWest_{suffix}",
        "actor_type": "StaticMeshActor",
        "asset_ref": {"path": "/Engine/BasicShapes/Cube.Cube"},
        "transform": {
            "location": {"x": -3000.0, "y": 4500.0, "z": 400.0},
            "rotation": {"pitch": 0.0, "yaw": 0.0, "roll": 0.0},
            "scale": {"x": 20.0, "y": 10.0, "z": 4.0},
        },
        "tags": ["castle", "wall"],
    })
    # East wall
    objs.append({
        "scene_id": scene_id,
        "mcp_id": f"castle_wall_east_{suffix}",
        "desired_name": f"CastleWallEast_{suffix}",
        "actor_type": "StaticMeshActor",
        "asset_ref": {"path": "/Engine/BasicShapes/Cube.Cube"},
        "transform": {
            "location": {"x": 4500.0, "y": 0.0, "z": 400.0},
            "rotation": {"pitch": 0.0, "yaw": 0.0, "roll": 0.0},
            "scale": {"x": 10.0, "y": 50.0, "z": 4.0},
        },
        "tags": ["castle", "wall"],
    })
    # West wall
    objs.append({
        "scene_id": scene_id,
        "mcp_id": f"castle_wall_west_{suffix}",
        "desired_name": f"CastleWallWest_{suffix}",
        "actor_type": "StaticMeshActor",
        "asset_ref": {"path": "/Engine/BasicShapes/Cube.Cube"},
        "transform": {
            "location": {"x": -4500.0, "y": 0.0, "z": 400.0},
            "rotation": {"pitch": 0.0, "yaw": 0.0, "roll": 0.0},
            "scale": {"x": 10.0, "y": 50.0, "z": 4.0},
        },
        "tags": ["castle", "wall"],
    })

    # --- Corner towers (cube shaped, 6m x 6m base, 16m tall) ---
    tower_positions = [
        ("nw", -4500.0, -4500.0),
        ("ne", 4500.0, -4500.0),
        ("sw", -4500.0, 4500.0),
        ("se", 4500.0, 4500.0),
    ]
    for tower_suffix, tx, ty in tower_positions:
        objs.append({
            "scene_id": scene_id,
            "mcp_id": f"castle_tower_{tower_suffix}_{suffix}",
            "desired_name": f"CastleTower{tower_suffix.upper()}_{suffix}",
            "actor_type": "StaticMeshActor",
            "asset_ref": {"path": "/Engine/BasicShapes/Cube.Cube"},
            "transform": {
                "location": {"x": tx, "y": ty, "z": 800.0},
                "rotation": {"pitch": 0.0, "yaw": 0.0, "roll": 0.0},
                "scale": {"x": 3.0, "y": 3.0, "z": 16.0},
            },
            "tags": ["castle", "tower"],
        })

    # --- Gate pillars (3m x 3m, 8m tall) ---
    objs.append({
        "scene_id": scene_id,
        "mcp_id": f"castle_gate_pillar_e_{suffix}",
        "desired_name": f"CastleGatePillarE_{suffix}",
        "actor_type": "StaticMeshActor",
        "asset_ref": {"path": "/Engine/BasicShapes/Cube.Cube"},
        "transform": {
            "location": {"x": 800.0, "y": 4500.0, "z": 400.0},
            "rotation": {"pitch": 0.0, "yaw": 0.0, "roll": 0.0},
            "scale": {"x": 1.5, "y": 1.5, "z": 8.0},
        },
        "tags": ["castle", "gate"],
    })
    objs.append({
        "scene_id": scene_id,
        "mcp_id": f"castle_gate_pillar_w_{suffix}",
        "desired_name": f"CastleGatePillarW_{suffix}",
        "actor_type": "StaticMeshActor",
        "asset_ref": {"path": "/Engine/BasicShapes/Cube.Cube"},
        "transform": {
            "location": {"x": -800.0, "y": 4500.0, "z": 400.0},
            "rotation": {"pitch": 0.0, "yaw": 0.0, "roll": 0.0},
            "scale": {"x": 1.5, "y": 1.5, "z": 8.0},
        },
        "tags": ["castle", "gate"],
    })

    # --- Bridge (8m wide, 20m long, 0.2m thick) ---
    objs.append({
        "scene_id": scene_id,
        "mcp_id": f"castle_bridge_{suffix}",
        "desired_name": f"CastleBridge_{suffix}",
        "actor_type": "StaticMeshActor",
        "asset_ref": {"path": "/Engine/BasicShapes/Cube.Cube"},
        "transform": {
            "location": {"x": 0.0, "y": 5500.0, "z": 10.0},
            "rotation": {"pitch": 0.0, "yaw": 0.0, "roll": 0.0},
            "scale": {"x": 4.0, "y": 10.0, "z": 0.2},
        },
        "tags": ["castle", "bridge"],
    })

    # --- Keep (central stronghold, 16m x 16m, 20m tall) ---
    objs.append({
        "scene_id": scene_id,
        "mcp_id": f"castle_keep_{suffix}",
        "desired_name": f"CastleKeep_{suffix}",
        "actor_type": "StaticMeshActor",
        "asset_ref": {"path": "/Engine/BasicShapes/Cube.Cube"},
        "transform": {
            "location": {"x": 0.0, "y": 0.0, "z": 1000.0},
            "rotation": {"pitch": 0.0, "yaw": 0.0, "roll": 0.0},
            "scale": {"x": 8.0, "y": 8.0, "z": 20.0},
        },
        "tags": ["castle", "keep"],
    })

    # --- Barracks (two buildings inside the walls) ---
    objs.append({
        "scene_id": scene_id,
        "mcp_id": f"castle_barracks_1_{suffix}",
        "desired_name": f"CastleBarracks1_{suffix}",
        "actor_type": "StaticMeshActor",
        "asset_ref": {"path": "/Engine/BasicShapes/Cube.Cube"},
        "transform": {
            "location": {"x": -2500.0, "y": -2500.0, "z": 300.0},
            "rotation": {"pitch": 0.0, "yaw": 0.0, "roll": 0.0},
            "scale": {"x": 6.0, "y": 4.0, "z": 6.0},
        },
        "tags": ["castle", "barracks"],
    })
    objs.append({
        "scene_id": scene_id,
        "mcp_id": f"castle_barracks_2_{suffix}",
        "desired_name": f"CastleBarracks2_{suffix}",
        "actor_type": "StaticMeshActor",
        "asset_ref": {"path": "/Engine/BasicShapes/Cube.Cube"},
        "transform": {
            "location": {"x": 2500.0, "y": -2500.0, "z": 300.0},
            "rotation": {"pitch": 0.0, "yaw": 0.0, "roll": 0.0},
            "scale": {"x": 6.0, "y": 4.0, "z": 6.0},
        },
        "tags": ["castle", "barracks"],
    })

    return objs


def _apply_castle_scene(scene_id: str):
    apply = api_post("/sync/apply", {
        "scene_id": scene_id,
        "mode": "apply_safe",
        "allow_delete": False,
        "max_operations": 200,
    })
    return assert_success(apply, "apply castle")


def _missing_castle_mcp_ids(objects):
    level_result = unreal_command("get_actors_in_level", {})
    actors = level_result.get("result", {}).get("actors", [])
    actual_mcp_ids = {
        tag.removeprefix("mcp_id:")
        for actor in actors
        for tag in actor.get("tags", [])
        if tag.startswith("mcp_id:")
    }
    return [
        obj["mcp_id"]
        for obj in objects
        if obj["mcp_id"] not in actual_mcp_ids
    ]
