#pragma once

#include "CoreMinimal.h"
#include "AIController.h"
#include "CognitiveAIController.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnCognitiveDecisionCompleted, const FString&, DecisionString);

/**
 * AI Controller that simulates an on-device LLM processing environment.
 * Uses asynchronous tasks to offload "cognitive" processing (like LLM mock inference)
 * without blocking the main game thread, then synchronizes results back to the gamestate.
 */
UCLASS()
class FLOPPERAMUNREALMCP_API ACognitiveAIController : public AAIController
{
	GENERATED_BODY()

public:
	ACognitiveAIController();

	virtual void Tick(float DeltaTime) override;

	// Request the AI to process the current environment state using an async task
	UFUNCTION(BlueprintCallable, Category = "AI|Cognitive")
	void RequestCognitiveProcessing(const FString& EnvironmentalContext);

	UPROPERTY(BlueprintAssignable, Category = "AI|Cognitive")
	FOnCognitiveDecisionCompleted OnDecisionCompleted;

protected:
	virtual void BeginPlay() override;

	// Checks if there are completed async tasks to synchronize with the main thread
	void SynchronizeCognitiveState();

private:
	// Simulates an async LLM task running on a background thread
	void RunAsyncLLMTask(const FString& Context);

	FCriticalSection CognitiveMutex;

	// Queue of decisions generated by the async task
	TArray<FString> PendingDecisions;

	bool bIsProcessing;
};
